from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
STATIC_DIR = ROOT / "app" / "static"
CSS_SOURCES = (
    "style.css",
    "daily.css",
    "feedback.css",
    "v2.css",
    "v3.css",
    "v4.css",
    "demo.css",
)
BUNDLE_PATH = STATIC_DIR / "app.css"


def build_bundle() -> Path:
    sections = [
        "/* Generated by scripts/build_static_bundle.py. Edit the source CSS files. */\n"
    ]
    for name in CSS_SOURCES:
        content = (STATIC_DIR / name).read_text(encoding="utf-8").strip()
        sections.append(f"\n/* {name} */\n{content}\n")
    BUNDLE_PATH.write_text("".join(sections), encoding="utf-8", newline="\n")
    return BUNDLE_PATH


if __name__ == "__main__":
    print(build_bundle())
